# Generated by Django 6.0.3 on 2026-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position_text', models.CharField(blank=True, max_length=50)),
                ('team_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['rank', 'name', 'player_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='externalplayerstat',
            name='unique_player_per_external_batch',
        ),
        migrations.RemoveConstraint(
            model_name='playerrankingsnapshot',
            name='unique_player_per_ranking_snapshot',
        ),
        migrations.RemoveField(
            model_name='playerrankingsnapshot',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='ExternalPlayerStat',
        ),
        migrations.DeleteModel(
            name='ExternalStatsBatch',
        ),
        migrations.DeleteModel(
            name='PlayerRankingSnapshot',
        ),
        migrations.DeleteModel(
            name='RankingSnapshot',
        ),
    ]
