# Generated by Django 6.0.3 on 2026-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
        migrations.AddField(
            model_name='player',
            name='appearances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='man_of_the_match',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
