# Generated by Django 6.0.3 on 2026-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_player_competitions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
